#!/bin/sh -e
#
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
date
git stash --include-untracked
git pull --rebase
make
sudo make install

echo "sbitx has been installed successfully."
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"

